cluster:
  # The count here corresponds to the number of Kubernetes nodes required for
  # the delpoyment, as StatefulSet has `podAntiAffinity` setup.
  replicaCount: 3

  # serviceName is used for the Kubernetes Service name. This is also used for
  # Pod and ConfigMap.
  serviceName: my-nats-jetstream

  # clusterName is used for NATS JetStream clustering.
  clusterName: my-jetstream-cluster

  volumeSpace: 100Mi
