---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.cluster.serviceName }}
  labels:
    app.kubernetes.io/name: {{ $.Values.cluster.serviceName }}
spec:
  selector:
    app.kubernetes.io/name: {{ $.Values.cluster.serverName }}
  clusterIP: None
  ports:
    - name: client
      port: 4222
    - name: cluster
      port: 6222
    - name: monitor
      port: 8222
    - name: metrics
      port: 7777
    - name: leafnodes
      port: 7422
    - name: gateways
      port: 7522
